require "user.launch"
require "user.options"
require "user.keymaps"
require "user.autocmds"
spec "user.colorscheme"
spec "user.devicons"
spec "user.treesitter"
spec "user.mason"
spec "user.schemastore"
spec "user.lspconfig"
spec "user.cmp"
spec "user.telescope"
spec "user.none-ls"
spec "user.illuminate"
spec "user.whichkey"
spec "user.nvimtree"
spec "user.lualine"
spec "user.navic"
spec "user.breadcrumbs"
spec "user.extras.neoscroll"
spec "user.extras.oil"
-- spec "user.extras.harpoon"
-- require "user.autocmds"
require "user.lazy"
